### ISSUE TITLE
Image Maind never works not a clue why

### ISSUE THREAD

**Issue by morpheus2n2** [meisnate12/Plex-Image-Cleanup#80]
### Version Number

1.1.1

### What branch are you on?

master

### Describe the Bug

I get this error everytime but I have no clue how to fix it.

```
"| Scanning Metadata Directory For Bloat Images: A:\Plex Media Server\Metadata                        |
| Scanning Metadata for Bloat Images: 124052 directories [01:54, 1084.08 directories/s]
| 898 Bloat Images Found                                                                             |
| Runtime: 0:01:54                                                                                   |
|                                                                                                    |
| Moving Bloat Images                                                                                |
| Moving Bloat Images:   0%|                                                               | 0/898 [00:00<?, ? moved/s]
| MOVE: A:\Plex Media Server\Metadata\Albums\0\116ad21db52e5956b0fccab9eaff10b66e5dce4.bundle\Uploads\posters\31631312b943f6f6ee3afd85d92fd7587e2d1ca7 --> A:\Plex Media Server\PIC Restore\Albums\0\116ad21db52e5956b0fccab9eaff10b66e5dce4.bundle\Uploads\posters\31631312b943f6f6ee3afd85d92fd7587e2d1ca7.jpg |
| Traceback (most recent call last):                                                                 |
|   File "A:\PlexBackend\ImageMaid\plex_image_cleanup.py", line 321, in run_plex_image_cleanup       |
|     util.move_path(path, meta_dir, restore_dir, suffix=".jpg")                                     |
|   File "C:\Users\Paul\AppData\Local\Programs\Python\Python312\Lib\site-packages\pmmutils\util.py", line 60, in move_path |
|     final_path.parent.mkdir(exist_ok=True)                                                         |
|   File "C:\Users\Paul\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1311, in mkdir |
|     os.mkdir(self, mode)                                                                           |
| FileNotFoundError: [WinError 3] The system cannot find the path specified: 'A:\\Plex Media Server\\PIC Restore\\Albums\\0\\116ad21db52e5956b0fccab9eaff10b66e5dce4.bundle\\Uploads\\posters' |
|                                                                                                    |
| [WinError 3] The system cannot find the path specified: 'A:\\Plex Media Server\\PIC Restore\\Albums\\0\\116ad21db52e5956b0fccab9eaff10b66e5dce4.bundle\\Uploads\\posters' |"
```

**Comment by morpheus2n2** [comment]
Hi can anyone help with this?

**Comment by darac** [comment]
This looks like a duplicate of #28 ?
